# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'TODOs'},
        ),
    ]
