# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160506_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
