# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20160506_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deleted TODOs',
            },
        ),
    ]
