# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20160507_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
